export const APP_NAME = 'i-pos'
export const APP_DOMAIN = 'https://www.ipostaxi.com'
export const COMPANY_NAME = 'Fineros'
export const USER_NAME = 'Emre Yıldız'
export const USER_INITIALS = 'EY'
export const USER_EMAIL = 'emre.yildiz@fineros.com.tr'
